# Generated by Django 3.0.8 on 2020-07-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cake_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='writer',
        ),
    ]
