# Generated by Django 3.0.8 on 2020-07-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200710_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cake',
            new_name='Basic',
        ),
    ]
